env: 
  TARGET_URL: 'https://web-frontend-1test-tools.apps.cluster-61f2.61f2.sandbox1569.opentlc.com/' # Set env variable for the target website for OWASP to scan

name: 'OWASP Full Scan Template'
on:
  push: #Any push will trigger this action
    branches: [ main ]

#Begin Job of scanning the website, 
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          #Update the line below with the branch target you wish to scan
          ref: main

        #Full Zap Scan
      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: ${{ env.TARGET_URL }}
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -d'
          issue_title: OWASP Full
